### ISSUE TITLE
Many of those links don't support or work 

### ISSUE THREAD

**Issue by BIGEAZY289** [ahmar20/com.aa.tvshows#7]

**Comment by ahmar20** [comment]
Can you provide more detail? Name of the TV Show or Episode? Any particular web hoster?

**Comment by BIGEAZY289** [comment]
Clipwatching ,mixdrop,abcvideo

**Comment by BIGEAZY289** [comment]
And many more

**Comment by ahmar20** [comment]
Please provide name of the TV show and/or episode where you are experiencing issues.

**Comment by BIGEAZY289** [comment]
Lucifer , The Boys

**Comment by ahmar20** [comment]
Which episode?

**Comment by BIGEAZY289** [comment]
1 and so on

**Comment by ahmar20** [comment]
Alright I'm looking into it.

**Update:** I have improved abcvideo.cc logic but clipwatching.com is refusing to load within the app but is working fine through a browser so will need to dig deeper for a fix. Although it could be a temporary issue and may fix itself pretty soon. 
**Update 2:** clipwatching.com seems to be working fine and it could be a geo-restriction that it's not working for you. Try the [troubleshooting guide](https://github.com/ahmar20/com.aa.tvshows#troubleshooting-guide).

**Comment by BIGEAZY289** [comment]
App need more ui optimization it looks not that attractive at this time

**Comment by ahmar20** [comment]
If you have any suggestions, you can point them out.

**Comment by BIGEAZY289** [comment]
What about adding websites like lookmovie and fmovies

**Comment by ahmar20** [comment]
There is no such plan to add support for movies at the moment.

**Comment by BIGEAZY289** [comment]
They have tv shows as well

**Comment by ahmar20** [comment]
I think everything is available on the server I am using and the video hosts are also probably the same. It's just a matter of reverse engineering the video hosts to get the video links.

**Comment by BIGEAZY289** [comment]
No one use my cloud and streamango and second one I don't only one server

**Comment by ahmar20** [comment]
I am going to close this issue because this cannot be resolved due to some video hosts requiring user input to access video.
